name: Validate push commits on ubuntu
on: [push] 
jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Checkout build core-image-minimal image
        run: |
          cd ${{ github.workspace }}
          git branch
          git remote add upstream https://git.yoctoproject.org/meta-intel
          git fetch upstream
          VAR=$(git diff --name-only master-dev upstream/master | awk -F"/" '{print $NF}' | awk '/.bb/{print}' | awk -F"_" '{print $1}' | awk -F".bb" '{print $1}')
          echo $VAR
      - name: conditional command
        run: |
          if [ -z "$VAR" ]; then
              # run the one command
              kas checkout kas/intel-corei7-64-minimal.yml
          else
              # run the other command
              kas build kas/intel-corei7-64-minimal.yml --target $VAR
          fi
          cat build/conf/bblayers.conf
      - run: echo "🍏 This job's status is ${{ job.status }}."
