name: Validate push commits on ubuntu
on: [push] 
jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build image/recipes
        run: |
          cd ${{ github.workspace }}
          git branch
          cat .git/config
          git remote add upstream https://git.yoctoproject.org/meta-intel
          echo "NNN"
          git fetch upstream
          echo "PPP"
          VAR=$(git diff --name-only upstream/master | awk -F"/" '{print $NF}' | awk '/.bb/{print}' | awk -F"_" '{print $1}' | awk -F".bb" '{print $1}')
          echo "recipes updated: " $VAR
          git remote remove upstream
          export KAS_TARGET="$VAR"
          if [ -z "$VAR" ]; then
              # Just run kas repo checkout
              kas checkout kas/intel-corei7-64-minimal.yml
          else
              # Build affected recipe targets
              kas build kas/intel-corei7-64-minimal.yml
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."
